### ISSUE TITLE
Running the face recognition module

### ISSUE THREAD

**Issue by apophatique** [grigorisg9gr/polynomial_nets#1]
Hi, i'm new to machine learning

I have a faces database - it is just a directory with faces image which are named as man's name on photo. I need to recognize all people from the database in input image
Can you please tell me how to run face recognition module to complete this task? I only see train.py, but no test.py

Thanks

**Comment by grigorisg9gr** [comment]
As we mention in the readme in the folder, the code follows standard techniques and evaluations. Specifically, our code modifies the ArcFace original repo; you can use the evaluation code provided there: https://github.com/deepinsight/insightface/tree/master/evaluation/IJB

Make sure that you are using Π-net network for your loaded weights.

**Comment by apophatique** [comment]
Could you add test.py, please? @grigorisg9gr

**Comment by sushidelivery** [comment]
hello!

yes, that would be great if you could add test.py!

thank you!!!

**Comment by grigorisg9gr** [comment]
We appreciate your interest, however we are busy this period. Feel free to make a pull request if you believe it's very different from the instructions we provide above. Thanks for understanding.

**Comment by Farah-Oubelkas** [comment]
Hello @grigorisg9gr!
Can you please elaborate more on how to use Π-net network so I can load the weights? How can I use the json file and parameter file provided to test it?

**Comment by jiankangdeng** [comment]
> Hello @grigorisg9gr!
> Can you please elaborate more on how to use Π-net network so I can load the weights? How can I use the json file and parameter file provided to test it?

load the model first and then get the feature embedding for the face image
https://github.com/grigorisg9gr/polynomial_nets/blob/master/face_recognition/eval/verification.py#L555

https://github.com/deepinsight/insightface/blob/master/recognition/_evaluation_/ijb/ijb_evals.py#L25
https://github.com/deepinsight/insightface/blob/master/recognition/_evaluation_/ijb/ijb_evals.py#L38
