### ISSUE TITLE
Can not download the face recognition pre-train model

### ISSUE THREAD

**Issue by kobkrit** [grigorisg9gr/polynomial_nets#2]
Seem link is dead: https://www.dropbox.com/sh/0kh42qinncf73q9/AAA9J2mAewa48P-xXsIPOAdia?dl=0

**Comment by grigorisg9gr** [comment]
Thank you for bringing it to our attention. 

How about this link? 
https://www.dropbox.com/sh/vf3fou3furz1llw/AADKVQztBZVeyD4XpvU32Z19a
