### ISSUE TITLE
Question about Licence

### ISSUE THREAD

**Issue by yabahu** [grigorisg9gr/polynomial_nets#5]
As your Face-recognition implementation is a minor alteration to Arcface (MIT-licenced), we are just wondering do you have any plans of using **MIT licence** for your modification to Arcface and pre-trained models.

Cheers | Yabahu

**Comment by grigorisg9gr** [comment]
Dear @yabahu, thanks for your interest in our work. 

Even in Arcface, the training data containing the annotations are available for non-commercial research purposes only. Specifically, the licenses might differ per dataset, so we encourage you to visit the corresponding pages. 

For our code, the license is 'Attribution-NonCommercial 4.0 International License' as mentioned here: https://github.com/grigorisg9gr/polynomial_nets/blob/master/LICENSE.txt
